name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src-tauri/**'
      - 'src/**'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above)
            args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs
          #   args: '--target x86_64-apple-darwin'
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Generate app version from package.json
        id: get_version
        # if: matrix.platform == 'macos-latest'
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "--------------------------------"
          echo "The current version is: $VERSION"
          echo "--------------------------------"

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      # End ----------------------------------

      # Update Tauri pubkey start ----------------------------------
      - name: Update Tauri pubkey
        env:
          TAURI_SIGNING_PUBLIC_KEY: ${{ secrets.TAURI_SIGNING_PUBLIC_KEY }}
        run: node scripts/update-tauri-pubkey.js
      # End ----------------------------------

      # Generate changelog start ----------------------------------
      - name: Generate Changelog
        id: generate_changelog
        if: matrix.platform == 'macos-latest'
        run: |
          # Read and store changelog content
          CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      # End ----------------------------------


      # Build and upload release
      - uses: tauri-apps/tauri-action@v0
        name: Build and upload release
        id: tauri_build
        timeout-minutes: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v${{ env.VERSION }}
          releaseName: 'v${{ env.VERSION }}'
          releaseBody: ${{ env.CHANGELOG }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
