name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above)
            args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs
          #   args: '--target x86_64-apple-darwin'
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: pnpm install

      - name: Get version from package.json
        id: get_version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Read Changelog
        id: changelog
        shell: bash
        run: |
          # Read the changelog file and capture the output
          CHANGELOG_CONTENT=$(cat CHANGELOG.md)
          
          # Save changelog to GitHub Environment
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ env.VERSION }}
          releaseName: 'App v${{ env.VERSION }}'
          releaseBody: ${{ env.CHANGELOG }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      # Only run on windows-latest to avoid concurrent updates
      - name: Update release.json
        if: matrix.platform == 'windows-latest'
        run: |
          # Checkout release branch
          git fetch origin release:release
          git checkout release

          # Create release.json with proper URLs
          cat > release.json << EOF
          {
            "version": "${{ env.VERSION }}",
            "notes": ${{ env.CHANGELOG }},
            "pub_date": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "platforms": {
              "darwin-aarch64": {
                "signature": "dW5kZWZpbmVk",
                "url": "https://github.com/hudy9x/uml/releases/download/v${{ env.VERSION }}/uml.app.tar.gz"
              },
              "windows-x86_64": {
                "signature": "dW5kZWZpbmVk",
                "url": "https://github.com/hudy9x/uml/releases/download/v${{ env.VERSION }}/uml.msi.zip"
              }
            }
          }
          EOF

          # Configure git
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Commit and push
          git add release.json
          git commit -m "Update release.json for version ${{ env.VERSION }}"
          git push origin release